
name: paython pipeline

on: push

jobs:
  test:
    runs-on : upuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: run command
        run: paython hello.py
        
  build:
     needs: [test]
     runs-on : upuntu-latest
     steps:
     - name: checkout code
       uses: actions/checkout@v3
     - name: Upload a Build Artifact
       uses: actions/upload-artifact@v3.1.2
       with:
         name: hello
         path: .
         
